image: mcr.microsoft.com/dotnet/core/sdk:3.1-buster

stages:
  - compile
  - test
  - grade

variables:
  VERSION: '1'

compile:
  stage: compile
  script:
    - dotnet build
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths: 
      - "*/bin/*/*/*"

.test:
  stage: test
  allow_failure: true
  script:
    - dotnet test --logger trx --filter "$TEST_FILTER"
  after_script:
    - bash ./extractTestResults.sh $TEST_REPORT
  artifacts:
    when: always
    paths: 
    - tests/$TEST_REPORT.txt

test:version:
  variables:
    TEST_FILTER: (grading=true)&(version=$VERSION)
    TEST_REPORT: version$VERSION
  extends: .test

test:full:
  variables:
    TEST_FILTER: grading=true
    TEST_REPORT: full
  extends: .test
  
test:coverage:
  stage: test
  allow_failure: true
  before_script:
    - dotnet tool install -g dotnet-reportgenerator-globaltool
  script:
    - dotnet test --filter "grading!=true" --settings coverlet.runsettings
  after_script:
    - /root/.dotnet/tools/reportgenerator "-reports:*/TestResults/*/coverage.cobertura.xml" "-targetdir:./coverage" "-reporttypes:Html"
    - cat coverage/index.htm | grep "<tr><th>Line coverage:</th><td>" | sed -E "s/^.*<td>(([[:digit:]]|\.)+)%.*$/\1/" | awk '{ print $1/100 }' > coverage/line_rate.txt
  artifacts:
    when: always
    paths: 
    - "coverage/*"

grade:
  stage: grade
  script:
    - bash ./grade.sh $CI_COMMIT_REF_NAME
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths: 
    - "tests"
    - "*.svg"
    - "quality.md"
    - "report.md"
    - "coverage/*"
    